export interface BookAttributes {
  id: string;
  title: string;
  description: string;
  content: string;
  image: string | null;
  userId: string;
  category: string;
}


export enum BookCategories {
  // Fiction
  Fiction = "Fiction",
  LiteraryFiction = "Literary Fiction",
  HistoricalFiction = "Historical Fiction",
  ScienceFiction = "Science Fiction",
  Fantasy = "Fantasy",
  Horror = "Horror",
  Thriller = "Thriller",
  Mystery = "Mystery",
  Crime = "Crime",
  Romance = "Romance",
  ContemporaryRomance = "Contemporary Romance",
  ParanormalRomance = "Paranormal Romance",
  EroticFiction = "Erotic Fiction",
  Adventure = "Adventure",
  Western = "Western",
  Dystopian = "Dystopian",
  MagicalRealism = "Magical Realism",
  ShortStories = "Short Stories",
  GraphicNovel = "Graphic Novel",
  YoungAdult = "Young Adult",
  ChildrensFiction = "Children's Fiction",
  FairyTales = "Fairy Tales",
  Mythology = "Mythology",
  UrbanFantasy = "Urban Fantasy",
  Cyberpunk = "Cyberpunk",
  Steampunk = "Steampunk",
  AlternateHistory = "Alternate History",
  MilitaryFiction = "Military Fiction",
  SpyFiction = "Spy Fiction",
  Supernatural = "Supernatural",
  Paranormal = "Paranormal",
  Gothic = "Gothic",
  DarkFantasy = "Dark Fantasy",
  Comedy = "Comedy",
  Satire = "Satire",
  Drama = "Drama",
  Poetry = "Poetry",
  Classic = "Classic",

  // Non-Fiction
  Nonfiction = "Nonfiction",
  Biography = "Biography",
  Autobiography = "Autobiography",
  Memoir = "Memoir",
  History = "History",
  MilitaryHistory = "Military History",
  PoliticalScience = "Political Science",
  Philosophy = "Philosophy",
  Psychology = "Psychology",
  SelfHelp = "Self-Help",
  Health = "Health",
  Fitness = "Fitness",
  Nutrition = "Nutrition",
  Cookbook = "Cookbook",
  Travel = "Travel",
  Guidebook = "Guidebook",
  TrueCrime = "True Crime",
  Business = "Business",
  Economics = "Economics",
  Finance = "Finance",
  Investing = "Investing",
  Marketing = "Marketing",
  Entrepreneurship = "Entrepreneurship",
  Science = "Science",
  Physics = "Physics",
  Biology = "Biology",
  Chemistry = "Chemistry",
  Astronomy = "Astronomy",
  Technology = "Technology",
  Programming = "Programming",
  ArtificialIntelligence = "Artificial Intelligence",
  Mathematics = "Mathematics",
  Engineering = "Engineering",
  Environment = "Environment",
  Nature = "Nature",
  Animals = "Animals",
  Parenting = "Parenting",
  Relationships = "Relationships",
  Education = "Education",
  Language = "Language",
  Reference = "Reference",
  Art = "Art",
  Photography = "Photography",
  Music = "Music",
  Film = "Film",
  Sports = "Sports",
  Games = "Games",
  Crafts = "Crafts",
  Hobbies = "Hobbies",
  HomeGarden = "Home & Garden",
  Fashion = "Fashion",
  Humor = "Humor",
  Religion = "Religion",
  Spirituality = "Spirituality",
  NewAge = "New Age",
  Occult = "Occult",
  LGBTQ = "LGBTQ",
  Feminism = "Feminism",
  SocialSciences = "Social Sciences",
  Sociology = "Sociology",
  Anthropology = "Anthropology",
  CulturalStudies = "Cultural Studies",
  Law = "Law",
  Medical = "Medical",
  Textbook = "Textbook",
  Academic = "Academic",
  Research = "Research",

  // Other
  Anthology = "Anthology",
  Essays = "Essays",
  Letters = "Letters",
  Diaries = "Diaries",
  Journals = "Journals",
  Quotes = "Quotes",
  Trivia = "Trivia",
  Puzzles = "Puzzles",
  Comics = "Comics",
  Manga = "Manga",
  LightNovel = "Light Novel",
  FanFiction = "Fan Fiction",
  Erotica = "Erotica",
  Other = "Other"
}